# // для postgres
#
#spring:
#  profiles:
#    active: postgres # По умолчанию используем Postgres
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/manymilk_bd
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database: postgresql
#    show-sql: false
#    open-in-view: false
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob:
#          non_contextual_creation: true

logging:
  level:
    root: INFO
    org.springframework.boot: OFF
    org.hibernate: OFF
    org.hibernate.SQL: OFF
    org.hibernate.type: OFF
    org.hibernate.tool.hbm2ddl: OFF

server:
 address: 0.0.0.0
 port: 8080

# кастомный пароль и логин
admin:
  username: admin
  password: adminZqT1
#

#server:
#  server.address=0.0.0.0
#  server.port=${PORT:8080}

yandex:
  disk:
    token: "y0__xCPi_G5CBjG2DognMikzBR5c4QfZiMNLoernzIVKoxup9gOBg"

spring:
  datasource:
    url: jdbc:h2:file:./data/manymilk
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    cache: false

  main:
    allow-bean-definition-overriding: true