# // для postgres
#
#spring:
#  profiles:
#    active: postgres # По умолчанию используем Postgres
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/manymilk_bd
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database: postgresql
#    show-sql: false
#    open-in-view: false
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob:
#          non_contextual_creation: true

spring:
  datasource:
    url: jdbc:h2:file:./data/manymilk   # база будет храниться в папке ./data
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # update = не удаляет данные, только обновляет структуру
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console   # веб-консоль по адресу http://localhost:8080/h2-console
  thymeleaf:
    cache: false

  main:
    allow-bean-definition-overriding: true